import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Registrator from './component/registrator'

const Home: NextPage = () => {
  const [see, setSee] = useState(true);
  async function Start() {
    setSee(false)
  }
  function HelloKitty() {
    if (see) {
      return (
        <div className={styles.grid}>
          <button className={styles.card} onClick={Start}>
            Подать документы
          </button>
        </div>
      )
    } else {
      return (
        <div className={styles.grid}>
          <Registrator/>
        </div>
      )
    }
  }
  async function Admin() {
    document.location.href= await "/admin"
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>ПРИЕМНАЯ КОМИССИЯ ХКОТСО</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icoo" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          КГБ ПОУ ХКОТСО
        </h1>

        <p className={styles.description}>
          Хотите получить среднее профессиональное образование?
        </p>
        <div>{HelloKitty()}</div>
      </main>

      <footer className={styles.footer}>
      <div className={styles.code} onClick={Admin}>Приемная комиссия КГБ ПОУ ХКОТСО 2022</div>
      </footer>
    </div>
  )
}

export default Home
